stages:
  - test

unittest:
  stage: test
  script:
    - setsid ./ci/tests.sh
  only:
    refs:
      - /^(main.*)$/
    changes:
      - .gitlab-ci.yml
      - ci/tests.sh
      - todoapi/*
      - todoapi/tests/*
  tags:
    - training_unittest
