stages:
  - mirror
  - test

mirror:
  stage: mirror
  script:
    - setsid ./ci/mirror.sh
  only:
    - /^(main.*)$/
  tags:
    - mirror

unittest:
  stage: test
  script:
    - setsid ./ci/tests.sh
  only:
    refs:
      - /^(main.*)$/
    changes:
      - .gitlab-ci.yml
      - ci/tests.sh
      - todoapi/*
      - todoapi/tests/*
  tags:
    - training_unittest

