stages:
  - test

unittest:
  stage: test
  script:
    - setsid ./ci/docker-deliver.sh "cmd-api" "2.11" "x86"
  only:
    refs:
      - /^(main.*)$/
    changes:
      - .gitlab-ci.yml
      - ci/test.sh
      - todoapi/*
      - todoapi/tests/*
  tags:
    - unittest_training
