version: "3.8"

services:
  todo_db:
    image: postgres:9.4
    container_name: todo_db
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=todo_passwd_456
      - POSTGRES_USER=todo
      - POSTGRES_DB=todo
    volumes:
      - ./data_volume:/var/lib/postgresql/data:z
    networks:
      - todo_api
    ports:
      - 5435:5432
  todo_api:
    image: harbor.comwork.io/todoapi/api:latest
    container_name: todo_api
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      target: todo_api
    networks:
      - todo_api
    depends_on: 
      - todo_db
    ports:
      - 5000:5000
    env_file: 
      - .env
  todo_unit_tests:
    image: harbor.comwork.io/todoapi/unittest:latest
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      target: todo_api
    command: ["python", "-m", "unittest"]

networks:
  todo_api:
    driver: bridge
